/**
 * dsh-plugin-desktop-shortcut
 *
 * A DeepSeek Harness (dsh) plugin that creates a Windows desktop shortcut
 * which launches `dsh web` with a double-click.
 *
 * Features
 * - Auto-installs the desktop shortcut when the plugin loads (`autoInstall`).
 * - Registers a `/shortcut` slash command when the TUI commands service is
 *   composed: `/shortcut`, `/shortcut install|ensure`, `/shortcut remove`,
 *   `/shortcut status`.
 * - Zero runtime dependencies (Node builtins only). Windows-only.
 *
 * @module dsh-plugin-desktop-shortcut
 */

import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, writeFileSync, rmSync } from 'node:fs'
import path from 'node:path'

/** Cordis plugin name used by loader diagnostics. */
export const name = 'desktop-shortcut'

const IS_WIN = process.platform === 'win32'
const USAGE = '/shortcut [install|remove|status]'

/* ------------------------------------------------------------------ */
/* Options resolution                                                  */
/* ------------------------------------------------------------------ */

/**
 * Resolve effective options from the plugin config object.
 * @param {Record<string, unknown>} [config] - Cordis plugin config (2nd arg of apply).
 * @returns {{dshDir: string, port: number, desktopName: string, autoInstall: boolean, launcherPath: string, desktopPath: string}}
 */
function resolveOptions(config = {}) {
  const dshDir = String(config.dshDir ?? process.cwd())
  const port = Number(config.port ?? 3080)
  const desktopName = String(config.desktopName ?? 'DSH Web')
  const launcherPath = String(config.launcherPath ?? path.join(dshDir, 'start-dsh-web.cmd'))
  const desktopPath = String(
    config.desktopPath
    ?? path.join(resolveDesktopDir(), `${desktopName}.lnk`),
  )
  return {
    dshDir,
    port,
    desktopName,
    autoInstall: config.autoInstall !== false,
    launcherPath,
    desktopPath,
  }
}

/* ------------------------------------------------------------------ */
/* Windows helpers                                                     */
/* ------------------------------------------------------------------ */

/** Resolve the real Desktop folder (handles OneDrive redirection). */
function resolveDesktopDir() {
  const r = spawnSync(
    'powershell.exe',
    ['-NoProfile', '-Command', "[Environment]::GetFolderPath('Desktop')"],
    { encoding: 'utf8' },
  )
  const line = (r.stdout || '').split(/\r?\n/).find(Boolean)
  if (r.status === 0 && line) return line.trim()
  return path.join(process.env.USERPROFILE || os_homedir(), 'Desktop')
}

/** Node's os.homedir, imported lazily to keep top-level imports minimal. */
function os_homedir() {
  // eslint-disable-next-line global-require -- plain-JS fallback
  return process.env.HOME || process.env.USERPROFILE || '.'
}

/** Resolve the pnpm executable used to launch dsh. */
function resolvePnpm() {
  // 1. npm_execpath is set when dsh was launched under pnpm/npm.
  const exec = process.env.npm_execpath
  if (exec && /pnpm/i.test(exec) && existsSync(exec)) return exec
  // 2. Ask the shell which pnpm is on PATH.
  const r = spawnSync('where.exe', ['pnpm'], { encoding: 'utf8' })
  if (r.status === 0) {
    const line = (r.stdout || '').split(/\r?\n/).find(Boolean)
    if (line) return line.trim()
  }
  // 3. Fall back to PATH lookup at run time.
  return 'pnpm'
}

/** Render the .cmd launcher content. */
function renderLauncher(options, pnpm) {
  return [
    '@echo off',
    'REM Auto-generated by dsh-plugin-desktop-shortcut. Delete with: /shortcut remove',
    `cd /d "${options.dshDir}"`,
    `echo [DSH] Starting DeepSeek Harness Web (http://127.0.0.1:${options.port}) ...`,
    'echo [DSH] Keep this window open while you use the web UI; closing it stops the service.',
    `"${pnpm}" dsh web`,
    'echo.',
    'echo [DSH] Service stopped.',
    'pause',
    '',
  ].join('\r\n')
}

/** Create a Windows .lnk via PowerShell COM. */
function createShortcut(shortcutPath, targetPath, workingDirectory, description) {
  const ps = [
    '$ws = New-Object -ComObject WScript.Shell',
    `$lnk = $ws.CreateShortcut(${JSON.stringify(shortcutPath)})`,
    `$lnk.TargetPath = ${JSON.stringify(targetPath)}`,
    `$lnk.WorkingDirectory = ${JSON.stringify(workingDirectory)}`,
    `$lnk.Description = ${JSON.stringify(description)}`,
    '$lnk.WindowStyle = 1',
    '$lnk.Save()',
  ].join('; ')
  const r = spawnSync('powershell.exe', ['-NoProfile', '-Command', ps], { encoding: 'utf8' })
  return r.status === 0
}

/* ------------------------------------------------------------------ */
/* Operations                                                          */
/* ------------------------------------------------------------------ */

/** Write the launcher script and create the desktop shortcut. */
function installShortcut(options) {
  if (!IS_WIN) {
    throw new Error('this plugin is Windows-only (process.platform is not win32)')
  }
  const pnpm = resolvePnpm()
  const launcherDir = path.dirname(options.launcherPath)
  if (!existsSync(launcherDir)) mkdirSync(launcherDir, { recursive: true })
  writeFileSync(options.launcherPath, renderLauncher(options, pnpm), { encoding: 'utf8' })

  const created = !existsSync(options.desktopPath)
  const ok = createShortcut(
    options.desktopPath,
    options.launcherPath,
    path.dirname(options.launcherPath),
    `Launch DeepSeek Harness Web (http://127.0.0.1:${options.port})`,
  )
  if (!ok) throw new Error('failed to create the desktop shortcut via PowerShell')
  return {
    kind: 'success',
    text: [
      `Desktop shortcut: ${ok ? 'created' : 'updated'}`,
      `  Shortcut: ${options.desktopPath}`,
      `  Launcher: ${options.launcherPath}`,
      `  Target:   ${pnpm} dsh web (in ${options.dshDir})`,
      `  URL:      http://127.0.0.1:${options.port}`,
      created ? '' : 'The shortcut already existed and was refreshed.',
    ].filter(Boolean).join('\n'),
  }
}

/** Remove the desktop shortcut and the launcher script. */
function removeShortcut(options) {
  let removed = 0
  if (existsSync(options.desktopPath)) {
    rmSync(options.desktopPath, { force: true })
    removed += 1
  }
  if (existsSync(options.launcherPath)) {
    rmSync(options.launcherPath, { force: true })
    removed += 1
  }
  return {
    kind: 'success',
    text: removed === 0
      ? 'No desktop shortcut found; nothing to remove.'
      : `Removed ${removed} item(s):\n  ${options.desktopPath}\n  ${options.launcherPath}`,
  }
}

/** Report the current state of the shortcut. */
function statusShortcut(options) {
  const lines = [`Shortcut: ${options.desktopPath}`]
  if (existsSync(options.desktopPath)) {
    lines.push('  State: exists')
  } else {
    lines.push('  State: missing (run /shortcut install)')
  }
  lines.push(`Launcher: ${options.launcherPath}`)
  if (existsSync(options.launcherPath)) {
    lines.push('  State: exists')
  } else {
    lines.push('  State: missing')
  }
  lines.push(`URL: http://127.0.0.1:${options.port}`)
  if (!IS_WIN) lines.push('Note: this plugin only works on Windows.')
  return { kind: 'success', text: lines.join('\n') }
}

/* ------------------------------------------------------------------ */
/* Command handler                                                     */
/* ------------------------------------------------------------------ */

/** Execute one parsed `/shortcut` invocation. */
function handleShortcutCommand(options, invocation) {
  const raw = String(invocation.rawInput ?? '').trim().toLowerCase()
  try {
    if (raw === '' || raw === 'status') return statusShortcut(options)
    if (raw === 'install' || raw === 'ensure' || raw === 'create') return installShortcut(options)
    if (raw === 'remove' || raw === 'uninstall' || raw === 'delete') return removeShortcut(options)
    return { kind: 'error', text: `Unknown /shortcut subcommand "${raw}". Usage: ${USAGE}` }
  } catch (error) {
    return {
      kind: 'error',
      text: `desktop-shortcut: ${error instanceof Error ? error.message : String(error)}`,
    }
  }
}

/* ------------------------------------------------------------------ */
/* Plugin entry                                                        */
/* ------------------------------------------------------------------ */

/**
 * Cordis plugin entry.
 * @param {import('@deepseek-ai/cordis').Context} ctx - Plugin context.
 * @param {Record<string, unknown>} [config] - Plugin configuration.
 */
export function apply(ctx, config) {
  const options = resolveOptions(config)

  // Auto-install once the application is ready (best effort).
  ctx.on('ready', () => {
    if (!IS_WIN || !options.autoInstall) return
    try {
      const result = installShortcut(options)
      if (ctx.logger) ctx.logger.info(`desktop-shortcut: ${result.text}`)
    } catch (error) {
      if (ctx.logger) {
        ctx.logger.warn(`desktop-shortcut: auto-install failed: ${error instanceof Error ? error.message : String(error)}`)
      }
    }
  })

  // Register the /shortcut command when the commands service is composed.
  ctx.on('ready', () => {
    const commands = /** @type {{register?: (d: unknown) => unknown} | undefined} */ (ctx.commands)
    if (!commands || typeof commands.register !== 'function') return
    commands.register({
      name: 'shortcut',
      description: 'install, remove, or check the DSH web desktop shortcut (Windows)',
      input: { hint: '[install|remove|status]' },
      handler: invocation => handleShortcutCommand(options, invocation),
    })
  })
}
